package server

import (
	"context"
	"encoding/json"
	"net/http"
	"testing"
	"time"

	pio "github.com/qydysky/part/io"
	req "github.com/qydysky/part/reqf"
	pu "github.com/qydysky/part/unsafe"
	web "github.com/qydysky/part/web"
)

func Test1(t *testing.T) {
	sseSer := NewServer()
	mq := sseSer.MQ()
	{
		mq.Pull_tag(map[string]func(*Umsg) (disable bool){
			`init`: func(u *Umsg) (disable bool) {
				t.Log(`init`, u.Id)
				return false
			},
			`recv`: func(u *Umsg) (disable bool) {
				t.Log(`recv`, u.Id)
				if string(u.Data) == "ok" {
					mq.Push_tag(`send`, u.Set([]byte("id"), []byte("123")))
					mq.Push_tag(`send`, u.Set([]byte("data"), []byte("456")))
					mq.Push_tag(`send`, u.End())
					mq.Push_tag(`close`, new(Umsg))
				}
				t.Log(`recvf`, u.Id)
				return false
			},
			`error`: func(u *Umsg) (disable bool) {
				t.Log(u.Err)
				mq.Push_tag(`close`, u)
				return false
			},
			`fin`: func(u *Umsg) (disable bool) {
				t.Log(`fin`, u.Id)
				return false
			},
		})
	}

	ser := web.New(&http.Server{Addr: "127.0.0.1:9000"})
	defer ser.Shutdown()
	ser.Handle(map[string]func(http.ResponseWriter, *http.Request){
		`/sse/`: sseSer.Handle,
	})

	time.Sleep(time.Second)
	r := req.New()
	r.Reqf(req.Rval{
		Url:     "http://127.0.0.1:9000/sse/",
		PostStr: "ok",
	})
	r.Respon(func(b []byte) error {
		for s, i := 0, 0; i < len(b); i++ {
			if b[i] == '\n' && i != s {
				t.Log(string(b[s:i]))
				s = i + 1
			}
		}
		return nil
	})
}

func Test2(t *testing.T) {
	sseSer := NewServer()
	mq := sseSer.MQ()
	{
		mq.Pull_tag(map[string]func(*Umsg) (disable bool){
			`init`: func(u *Umsg) (disable bool) {
				t.Log(`init`, u.Id)
				return false
			},
			`recv`: func(u *Umsg) (disable bool) {
				t.Log(`recv`, u.Id)
				if string(u.Data) == "ok" {
					mq.Push_tag(`send`, u.Set([]byte("id"), []byte("123")))
					mq.Push_tag(`send`, u.Set([]byte("data"), []byte("456")))
					mq.Push_tag(`send`, u.End())
					mq.Push_tag(`close`, new(Umsg))
				}
				t.Log(`recvf`, u.Id)
				return false
			},
			`error`: func(u *Umsg) (disable bool) {
				t.Log(u.Err)
				mq.Push_tag(`close`, u)
				return false
			},
			`fin`: func(u *Umsg) (disable bool) {
				t.Log(`fin`, u.Id)
				return false
			},
		})
	}

	ser := web.New(&http.Server{Addr: "127.0.0.1:9000"})
	defer ser.Shutdown()
	ser.Handle(map[string]func(http.ResponseWriter, *http.Request){
		`/sse/`: sseSer.Handle,
	})

	time.Sleep(time.Second)
	r := req.New()
	pipe := pio.NewPipe()
	r.Reqf(req.Rval{
		Url:        "http://127.0.0.1:9000/sse/",
		PostStr:    "ok",
		SaveToPipe: pipe,
		Async:      true,
	})
	for f := range req.ResponSSE(pipe.Read) {
		t.Log(pu.B2S(f(pu.S2B("id"))))
		t.Log(pu.B2S(f(pu.S2B("data"))))
	}
}

func Test3(t *testing.T) {
	r := req.New()
	pipe := pio.NewPipe()
	ctx, cancle := context.WithTimeout(t.Context(), time.Second*5)
	defer cancle()
	r.Reqf(req.Rval{
		Ctx: ctx,
		Url: "https://sse.dev/test",
		Header: map[string]string{
			`Referer`:    `https://sse.dev/testpage.html`,
			`Accept`:     `text/event-stream`,
			`Connection`: `keep-alive`,
		},
		SaveToPipe: pipe,
		Async:      true,
	})
	type AutoGenerated struct {
		Testing bool   `json:"testing"`
		SseDev  string `json:"sse_dev"`
		Msg     string `json:"msg"`
		Now     int64  `json:"now"`
	}
	var a AutoGenerated
	for f := range req.ResponSSE(pipe.Read) {
		if e := json.Unmarshal(f(pu.S2B("data")), &a); e != nil {
			t.Fatal(e)
		} else {
			t.Log(a)
		}
	}
}

func Test4(t *testing.T) {
	r := req.New()
	rrr := req.NewRawReqRes()
	rrr.ReqClose()
	ctx, cancle := context.WithTimeout(t.Context(), time.Second*5)
	defer cancle()
	r.Reqf(req.Rval{
		Method: `GET`,
		Ctx:    ctx,
		Url:    "https://sse.dev/test",
		Header: map[string]string{
			`Referer`:    `https://sse.dev/testpage.html`,
			`Accept`:     `text/event-stream`,
			`Connection`: `keep-alive`,
		},
		RawPipe: rrr,
		Async:   true,
	})
	type AutoGenerated struct {
		Testing bool   `json:"testing"`
		SseDev  string `json:"sse_dev"`
		Msg     string `json:"msg"`
		Now     int64  `json:"now"`
	}
	var a AutoGenerated
	for f := range req.ResponSSE(rrr.ResRead) {
		if e := json.Unmarshal(f(pu.S2B("data")), &a); e != nil {
			t.Fatal(e)
		} else {
			t.Log(a)
		}
	}
}
