name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Test
      run: |
        go test -v .
        go test -v -race github.com/qydysky/part/signal
        go test -v -race github.com/qydysky/part/reqf
        go test -v -race github.com/qydysky/part/limit
        go test -v -race github.com/qydysky/part/file
        go test -v -race github.com/qydysky/part/pool
        go test -v -race github.com/qydysky/part/funcCtrl
        go test -v -race github.com/qydysky/part/msgq
