name: test

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Set Release Name
      run: |
        echo "TIME=$(date +"%Y%m%d%H%M%S")" >> $GITHUB_ENV
        echo "HASH=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

    - name: Upload a Release Asset
      uses: softprops/action-gh-release@v2
      with:
        body: go get github.com/qydysky/part@v0.28.${{ env.TIME }}
        tag_name: v0.28.${{ env.TIME }}